# Generated by Django 5.2.5 on 2025-10-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bola', 'Bola'), ('shoes', 'Shoes'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
